name: beta release

on:
  push:
    branches: [ 'main' ]

jobs:
  release:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        go-version: [ '1.21' ]
    name: Beta Release Changelog
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: changelog # or changelogithub@0.12 if ensure the stable result
        id: changelog
        run: |
          git tag -l
          npx changelogen@latest --output CHANGELOG.md
#        env:
#          GITHUB_TOKEN: ${{secrets.MY_TOKEN}}

      - name: Prerelease
        uses: tubone24/update_release@master
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
          TAG_NAME: beta
        with:
          prerelease: true
          body_path: CHANGELOG.md