name: Golang Formatter
on: [pull_request]
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0

      - name: Format code
        uses: iamnotaturtle/auto-gofmt@v2.1.0
        with:
          commit_message: "style: format code with gofmt"
          only_changed: True