name: release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        go-version: [1.17]
    name: Release
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

#      - name: Setup docker
#        uses: docker-practice/actions-setup-docker@master

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: v2
          path: alist
          persist-credentials: false
          fetch-depth: 0

      - name: Checkout web repo
        uses: actions/checkout@v2
        with:
          repository: Xhofe/alist-web
          ref: v2
          path: alist-web
          persist-credentials: false
          fetch-depth: 0

      - name: Set up xgo
        run: |
          docker pull techknowlogick/xgo:latest
          go install src.techknowlogick.com/xgo@latest
          sudo apt install upx

      - name: Build
        run: |
          mv alist/build.sh .
          bash build.sh release

      - name: Upload asserts files
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MY_TOKEN }}
          branch: cdn
          directory: alist-web
          repository: Xhofe/alist-web

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: alist/build/compress/*